package com.mazenmix.mxblueradar;

import android.Manifest;import android.app.*;import android.bluetooth.*;import android.bluetooth.le.*;import android.content.*;import android.content.pm.PackageManager;import android.os.*;
import java.util.*;

public final class BluetoothScanService extends Service{
 public static final String ACTION_START="com.mazenmix.mxblueradar.START",ACTION_STOP="com.mazenmix.mxblueradar.STOP";private static final int NID=4101;private static final long LOST=25000;
 private BluetoothAdapter adapter;private DeviceRepository repo;private final Handler h=new Handler(Looper.getMainLooper());private final Map<String,Float>smooth=new HashMap<>();private final Map<String,Long>first=new HashMap<>(),counts=new HashMap<>(),persist=new HashMap<>(),sighting=new HashMap<>();private final Map<String,Boolean>present=new HashMap<>();private boolean registered,scanning;
 @Override public void onCreate(){super.onCreate();repo=new DeviceRepository(this);BluetoothManager bm=(BluetoothManager)getSystemService(Context.BLUETOOTH_SERVICE);adapter=bm==null?null:bm.getAdapter();channels();classic();h.post(presenceTick);}
 @Override public int onStartCommand(Intent i,int flags,int id){if(i!=null&&ACTION_STOP.equals(i.getAction())){stopScanning();stopForeground(STOP_FOREGROUND_REMOVE);stopSelf();return START_NOT_STICKY;}startForeground(NID,fg());startScanning();return START_STICKY;}
 @Override public void onDestroy(){stopScanning();h.removeCallbacksAndMessages(null);if(registered)try{unregisterReceiver(rx);}catch(Exception ignored){}repo.close();super.onDestroy();}@Override public IBinder onBind(Intent i){return null;}
 private boolean scanPerm(){return Build.VERSION.SDK_INT>=31?checkSelfPermission(Manifest.permission.BLUETOOTH_SCAN)==PackageManager.PERMISSION_GRANTED:checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)==PackageManager.PERMISSION_GRANTED;}private boolean connPerm(){return Build.VERSION.SDK_INT<31||checkSelfPermission(Manifest.permission.BLUETOOTH_CONNECT)==PackageManager.PERMISSION_GRANTED;}
 private void startScanning(){if(scanning)return;if(adapter==null){ScanHub.setStatus("Bluetooth hardware unavailable");return;}if(!adapter.isEnabled()){ScanHub.setStatus("Bluetooth is off");return;}if(!scanPerm()){ScanHub.setStatus("Nearby devices permission required");return;}scanning=true;ScanHub.setScanning(true);ScanHub.setStatus("PHANTOM scan • BLE + Classic + intelligence");if(adapter.getBluetoothLeScanner()!=null){ScanSettings s=new ScanSettings.Builder().setScanMode(ScanSettings.SCAN_MODE_LOW_LATENCY).setReportDelay(0).build();try{adapter.getBluetoothLeScanner().startScan(Collections.singletonList(new ScanFilter.Builder().build()),s,ble);}catch(Exception e){ScanHub.setStatus("BLE scan permission denied");}}try{if(!adapter.isDiscovering())adapter.startDiscovery();}catch(Exception ignored){}}
 private void stopScanning(){if(!scanning)return;scanning=false;ScanHub.setScanning(false);ScanHub.setStatus("Paused");try{if(adapter!=null&&adapter.getBluetoothLeScanner()!=null&&scanPerm())adapter.getBluetoothLeScanner().stopScan(ble);}catch(Exception ignored){}try{if(adapter!=null&&scanPerm())adapter.cancelDiscovery();}catch(Exception ignored){}}
 private final ScanCallback ble=new ScanCallback(){@Override public void onScanResult(int t,ScanResult r){if(r!=null)ingest(r);}@Override public void onBatchScanResults(List<ScanResult>rs){if(rs!=null)for(ScanResult r:rs)ingest(r);}@Override public void onScanFailed(int e){ScanHub.setStatus("BLE scan error "+e+" • Classic still active");}};
 private void ingest(ScanResult r){BluetoothDevice d=r.getDevice();ScanRecord rec=r.getScanRecord();String name=DeviceClassifier.safeName(d,rec),fp=DeviceClassifier.ghostFingerprint(rec,name),key=DeviceClassifier.stableKey(d,fp),addr=addr(d);List<String>sv=DeviceClassifier.serviceUuids(rec);boolean mx=sv.contains(MxPeerManager.SERVICE_UUID.toString()),sos=sv.contains(EmergencyBeaconController.SOS_UUID.toString());int tx=rec==null?Integer.MIN_VALUE:rec.getTxPowerLevel();if(tx==Integer.MIN_VALUE||tx==127)tx=r.getTxPower();if(tx==127)tx=Integer.MIN_VALUE;int fl=rec==null?-1:rec.getAdvertiseFlags();merge(key,addr,name,r.getRssi(),tx,true,false,r.isConnectable(),mx,sos,DeviceClassifier.kind(d,name),DeviceClassifier.manufacturerSummary(rec),fp,sv,DeviceClassifier.addressType(addr),fl,r.getPrimaryPhy(),r.getSecondaryPhy(),r.getAdvertisingSid(),r.getPeriodicAdvertisingInterval(),DeviceClassifier.rawHex(rec),DeviceClassifier.serviceDataSummary(rec),DeviceClassifier.manufacturerDataSummary(rec));}
 private void ingestClassic(BluetoothDevice d,int rssi){String n=DeviceClassifier.safeName(d,null),fp="CLASSIC-"+addr(d).replace(":","");String key=DeviceClassifier.stableKey(d,fp);DeviceRecord o=ScanHub.get(key);merge(key,addr(d),n,rssi,Integer.MIN_VALUE,o!=null&&o.ble,true,true,o!=null&&o.mxPeer,o!=null&&o.sosBeacon,DeviceClassifier.kind(d,n),o==null?"":o.manufacturer,o==null?fp:o.ghostFingerprint,o==null?new ArrayList<>():o.serviceUuids,DeviceClassifier.addressType(addr(d)),-1,0,0,-1,0,o==null?"":o.rawAdvertisementHex,o==null?"":o.serviceDataSummary,o==null?"":o.manufacturerDataSummary);}
 private synchronized void merge(String key,String addr,String name,int rssi,int tx,boolean isBle,boolean classic,boolean connectable,boolean mx,boolean sos,String kind,String manufacturer,String fp,List<String>services,String addressType,int flags,int primary,int secondary,int sid,int interval,String raw,String serviceData,String mfgData){long now=System.currentTimeMillis();DeviceRecord old=ScanHub.get(key);float prev=smooth.containsKey(key)?smooth.get(key):(old==null?rssi:old.smoothedRssi);float sm=prev+.25f*(rssi-prev);smooth.put(key,sm);long f=first.containsKey(key)?first.get(key):(old==null?now:old.firstSeen);first.put(key,f);long count=counts.containsKey(key)?counts.get(key)+1:(old==null?1:old.seenCount+1);counts.put(key,count);if(old!=null){isBle|=old.ble;classic|=old.classic;mx|=old.mxPeer;sos|=old.sosBeacon;if(DeviceClassifier.nameQuality(name)<DeviceClassifier.nameQuality(old.name))name=old.name;if((manufacturer==null||manufacturer.isEmpty()))manufacturer=old.manufacturer;if((services==null||services.isEmpty()))services=old.serviceUuids;if(raw==null||raw.isEmpty())raw=old.rawAdvertisementHex;if(serviceData==null||serviceData.isEmpty())serviceData=old.serviceDataSummary;if(mfgData==null||mfgData.isEmpty())mfgData=old.manufacturerDataSummary;}
  DeviceRecord x=new DeviceRecord(key,addr,name,rssi,sm,tx,f,now,count,isBle,classic,connectable,mx,sos,kind,manufacturer,fp,services,addressType,flags,primary,secondary,sid,interval,raw,serviceData,mfgData);ScanHub.upsert(x);SignalStore.add(key,sm);Long lp=persist.get(key);if(lp==null||now-lp>5000){repo.upsert(x);persist.put(key,now);}Long ls=sighting.get(key);if(ls==null||now-ls>12000){repo.addSighting(x);sighting.put(key,now);}Boolean was=present.get(key);if(Boolean.FALSE.equals(was)){if(repo.isWatched(key))notifyWatch(x,true);AutomationEngine.arrival(this,x);}present.put(key,true);if(sos)notifySos(x);
 }
 private final Runnable presenceTick=new Runnable(){public void run(){long now=System.currentTimeMillis();for(DeviceRecord d:ScanHub.snapshot())if(now-d.lastSeen>LOST&&Boolean.TRUE.equals(present.get(d.key))){present.put(d.key,false);if(repo.isWatched(d.key))notifyWatch(d,false);AutomationEngine.departure(this,d);}ScanHub.prune(120000);if(scanning&&adapter!=null&&scanPerm())try{if(!adapter.isDiscovering())adapter.startDiscovery();}catch(Exception ignored){}h.postDelayed(this,5000);}};
 private void classic(){IntentFilter f=new IntentFilter();f.addAction(BluetoothDevice.ACTION_FOUND);f.addAction(BluetoothDevice.ACTION_NAME_CHANGED);f.addAction(BluetoothAdapter.ACTION_DISCOVERY_FINISHED);if(Build.VERSION.SDK_INT>=33)registerReceiver(rx,f,RECEIVER_NOT_EXPORTED);else registerReceiver(rx,f);registered=true;}
 private final BroadcastReceiver rx=new BroadcastReceiver(){public void onReceive(Context c,Intent i){String a=i.getAction();if(BluetoothDevice.ACTION_FOUND.equals(a)){BluetoothDevice d=Build.VERSION.SDK_INT>=33?i.getParcelableExtra(BluetoothDevice.EXTRA_DEVICE,BluetoothDevice.class):i.getParcelableExtra(BluetoothDevice.EXTRA_DEVICE);short r=i.getShortExtra(BluetoothDevice.EXTRA_RSSI,(short)-100);if(d!=null)ingestClassic(d,r);}else if(BluetoothDevice.ACTION_NAME_CHANGED.equals(a)){BluetoothDevice d=Build.VERSION.SDK_INT>=33?i.getParcelableExtra(BluetoothDevice.EXTRA_DEVICE,BluetoothDevice.class):i.getParcelableExtra(BluetoothDevice.EXTRA_DEVICE);String n=i.getStringExtra(BluetoothDevice.EXTRA_NAME);if(d!=null&&n!=null&&!n.trim().isEmpty()){String ad=addr(d);for(DeviceRecord o:ScanHub.snapshot())if(ad.equals(o.address)){merge(o.key,o.address,n.trim(),o.rssi,o.txPower,o.ble,o.classic,o.connectable,o.mxPeer,o.sosBeacon,DeviceClassifier.kind(d,n),o.manufacturer,o.ghostFingerprint,o.serviceUuids,o.addressType,o.advertiseFlags,o.primaryPhy,o.secondaryPhy,o.advertisingSid,o.periodicInterval,o.rawAdvertisementHex,o.serviceDataSummary,o.manufacturerDataSummary);break;}}}else if(BluetoothAdapter.ACTION_DISCOVERY_FINISHED.equals(a)&&scanning&&scanPerm())h.postDelayed(()->{try{if(adapter!=null&&!adapter.isDiscovering())adapter.startDiscovery();}catch(Exception ignored){}},1500);}}};
 private String addr(BluetoothDevice d){if(!connPerm())return "";try{return d.getAddress();}catch(Exception e){return "";}}
 private void channels(){if(Build.VERSION.SDK_INT>=26){NotificationManager n=getSystemService(NotificationManager.class);n.createNotificationChannel(new NotificationChannel("scan","Bluetooth scan activity",NotificationManager.IMPORTANCE_LOW));n.createNotificationChannel(new NotificationChannel("alerts","Device alerts",NotificationManager.IMPORTANCE_DEFAULT));n.createNotificationChannel(new NotificationChannel("sos","MX SOS nearby",NotificationManager.IMPORTANCE_HIGH));}}
 private Notification fg(){PendingIntent pi=PendingIntent.getActivity(this,0,new Intent(this,MainActivity.class),PendingIntent.FLAG_IMMUTABLE|PendingIntent.FLAG_UPDATE_CURRENT);return new Notification.Builder(this,"scan").setSmallIcon(R.drawable.ic_stat_bluetooth).setContentTitle("MX BlueRadar PHANTOM").setContentText("Bluetooth intelligence scan active").setContentIntent(pi).setOngoing(true).build();}
 private boolean notif(){return Build.VERSION.SDK_INT<33||checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)==PackageManager.PERMISSION_GRANTED;}
 private void notifyWatch(DeviceRecord d,boolean arrived){if(!notif())return;Notification n=new Notification.Builder(this,"alerts").setSmallIcon(R.drawable.ic_stat_bluetooth).setContentTitle(d.name).setContentText((arrived?"appeared nearby":"left the nearby area")+" • "+d.proximityLabel()).setAutoCancel(true).build();getSystemService(NotificationManager.class).notify(Math.abs(d.key.hashCode()),n);}
 private long lastSos;private void notifySos(DeviceRecord d){long now=System.currentTimeMillis();if(!notif()||now-lastSos<30000)return;lastSos=now;Notification n=new Notification.Builder(this,"sos").setSmallIcon(R.drawable.ic_stat_bluetooth).setContentTitle("MX SOS beacon detected").setContentText(d.name+" • "+Math.round(d.smoothedRssi)+" dBm").setAutoCancel(true).build();getSystemService(NotificationManager.class).notify(9911,n);}
}
