const json=(data,status=200,extra={})=>new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store",...extra}});
const cors={"access-control-allow-origin":"*","access-control-allow-methods":"GET,POST,DELETE,OPTIONS","access-control-allow-headers":"content-type,x-admin-key"};
async function sha256(value){const bytes=new TextEncoder().encode(value),digest=await crypto.subtle.digest("SHA-256",bytes);return[...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,"0")).join("")}
function randomKey(){const b=new Uint8Array(24);crypto.getRandomValues(b);return[...b].map(x=>x.toString(16).padStart(2,"0")).join("")}
function adminOk(request,env){const supplied=request.headers.get("x-admin-key")||"";return supplied.length>=8&&env.ADMIN_KEY&&supplied===env.ADMIN_KEY}
async function parseJson(request){try{return await request.json()}catch{return null}}
async function employeeAuth(env,employeeId,key){if(!employeeId||!key)return null;const employee=await env.DB.prepare("SELECT id,name,key_hash,enabled FROM employees WHERE id=?").bind(employeeId).first();if(!employee||!employee.enabled)return null;return await sha256(key)===employee.key_hash?employee:null}
export async function onRequest(context){
 const{request,env}=context;if(request.method==="OPTIONS")return new Response(null,{status:204,headers:cors});const url=new URL(request.url),route=url.pathname.replace(/^\/api\/?/,"");let response;
 try{
  if(route==="health"&&request.method==="GET")response=json({ok:true,service:"MX Field Tracker",now:Date.now()});
  else if(route==="track"&&request.method==="POST"){const body=await parseJson(request);if(!body)response=json({error:"Invalid JSON"},400);else{const employee=await employeeAuth(env,String(body.employeeId||"").trim().toUpperCase(),String(body.key||""));if(!employee)response=json({error:"Unauthorized employee"},401);else{const lat=Number(body.lat),lng=Number(body.lng);if(!Number.isFinite(lat)||!Number.isFinite(lng)||Math.abs(lat)>90||Math.abs(lng)>180)response=json({error:"Invalid coordinates"},400);else{const now=Date.now(),captured=Number(body.capturedAt)||now;await env.DB.prepare("INSERT INTO locations (employee_id,lat,lng,accuracy,speed,bearing,battery,captured_at,received_at,device,android) VALUES(?,?,?,?,?,?,?,?,?,?,?)").bind(employee.id,lat,lng,Number(body.accuracy)||0,Number(body.speed)||0,Number(body.bearing)||0,Number(body.battery)||-1,captured,now,String(body.device||"").slice(0,120),String(body.android||"").slice(0,40)).run();response=json({ok:true,receivedAt:now})}}}}
  else if(route==="shift"&&request.method==="POST"){const body=await parseJson(request);if(!body)response=json({error:"Invalid JSON"},400);else{const employee=await employeeAuth(env,String(body.employeeId||"").trim().toUpperCase(),String(body.key||""));if(!employee)response=json({error:"Unauthorized employee"},401);else{const at=Number(body.at)||Date.now();if(body.type==="start"){await env.DB.prepare("UPDATE shifts SET end_at=? WHERE employee_id=? AND end_at IS NULL").bind(at,employee.id).run();await env.DB.prepare("INSERT INTO shifts(employee_id,start_at,end_at) VALUES(?,?,NULL)").bind(employee.id,at).run()}else if(body.type==="end")await env.DB.prepare("UPDATE shifts SET end_at=? WHERE employee_id=? AND end_at IS NULL").bind(at,employee.id).run();else return json({error:"Invalid shift event"},400,cors);response=json({ok:true})}}}
  else if(route==="admin/employees"&&request.method==="GET"){if(!adminOk(request,env))response=json({error:"Unauthorized"},401);else{const rs=await env.DB.prepare(`SELECT e.id,e.name,e.enabled,e.created_at,l.lat,l.lng,l.accuracy,l.speed,l.bearing,l.battery,l.captured_at,l.received_at,l.device,l.android,(SELECT start_at FROM shifts s WHERE s.employee_id=e.id AND s.end_at IS NULL ORDER BY s.start_at DESC LIMIT 1) AS shift_start FROM employees e LEFT JOIN locations l ON l.id=(SELECT id FROM locations x WHERE x.employee_id=e.id ORDER BY x.received_at DESC LIMIT 1) ORDER BY e.name COLLATE NOCASE`).all();response=json({employees:rs.results||[],now:Date.now()})}}
  else if(route==="admin/employees"&&request.method==="POST"){if(!adminOk(request,env))response=json({error:"Unauthorized"},401);else{const body=await parseJson(request),id=String(body?.id||"").trim().toUpperCase().replace(/[^A-Z0-9_-]/g,"").slice(0,32),name=String(body?.name||"").trim().slice(0,80);if(!id||!name)response=json({error:"Employee ID and name are required"},400);else{const key=randomKey(),hash=await sha256(key);try{await env.DB.prepare("INSERT INTO employees(id,name,key_hash,enabled,created_at) VALUES(?,?,?,?,?)").bind(id,name,hash,1,Date.now()).run();response=json({ok:true,employee:{id,name},trackingKey:key})}catch{response=json({error:"Employee ID already exists"},409)}}}}
  else if(route.startsWith("admin/employees/")&&request.method==="DELETE"){if(!adminOk(request,env))response=json({error:"Unauthorized"},401);else{const id=decodeURIComponent(route.slice("admin/employees/".length)).toUpperCase();await env.DB.prepare("DELETE FROM locations WHERE employee_id=?").bind(id).run();await env.DB.prepare("DELETE FROM shifts WHERE employee_id=?").bind(id).run();await env.DB.prepare("DELETE FROM employees WHERE id=?").bind(id).run();response=json({ok:true})}}
  else if(route==="admin/history"&&request.method==="GET"){if(!adminOk(request,env))response=json({error:"Unauthorized"},401);else{const id=String(url.searchParams.get("id")||"").toUpperCase(),from=Number(url.searchParams.get("from"))||Date.now()-86400000,to=Number(url.searchParams.get("to"))||Date.now();const rs=await env.DB.prepare("SELECT lat,lng,accuracy,speed,bearing,battery,captured_at,received_at FROM locations WHERE employee_id=? AND received_at BETWEEN ? AND ? ORDER BY received_at ASC LIMIT 12000").bind(id,from,to).all();const shifts=await env.DB.prepare("SELECT start_at,end_at FROM shifts WHERE employee_id=? AND start_at <= ? AND COALESCE(end_at,?) >= ? ORDER BY start_at ASC").bind(id,to,to,from).all();response=json({id,points:rs.results||[],shifts:shifts.results||[]})}}
  else if(route==="admin/ping"&&request.method==="GET")response=adminOk(request,env)?json({ok:true}):json({error:"Unauthorized"},401);
  else response=json({error:"Not found"},404)
 }catch(e){response=json({error:"Server error",detail:String(e?.message||e).slice(0,300)},500)}
 const headers=new Headers(response.headers);Object.entries(cors).forEach(([k,v])=>headers.set(k,v));return new Response(response.body,{status:response.status,headers})
}